import os
import sqlite3
from contextlib import contextmanager
from typing import Optional

from .config import DATABASE_PATH, DATABASE_URL


def _is_postgres() -> bool:
    return bool(DATABASE_URL)


@contextmanager
def connection():
    if _is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()
    else:
        os.makedirs(os.path.dirname(DATABASE_PATH) or ".", exist_ok=True)
        conn = sqlite3.connect(DATABASE_PATH)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()


def init_db():
    if _is_postgres():
        with connection() as conn:
            conn.execute("""
            CREATE TABLE IF NOT EXISTS groups (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE
            )
            """)
            conn.execute("""
            CREATE TABLE IF NOT EXISTS lessons (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                group_id INTEGER NOT NULL,
                weekday INTEGER NOT NULL CHECK (weekday BETWEEN 1 AND 7),
                start_time TEXT NOT NULL,
                end_time TEXT NOT NULL,
                subject TEXT NOT NULL,
                teacher TEXT DEFAULT '',
                room TEXT DEFAULT '',
                notes TEXT DEFAULT '',
                FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE
            )
            """)
            conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                telegram_id BIGINT PRIMARY KEY,
                group_id INTEGER,
                FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE SET NULL
            )
            """)
            conn.execute("CREATE INDEX IF NOT EXISTS idx_lessons_group_day ON lessons(group_id, weekday, start_time)")
    else:
        with connection() as conn:
            conn.executescript("""
            CREATE TABLE IF NOT EXISTS groups (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE
            );
            CREATE TABLE IF NOT EXISTS lessons (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                group_id INTEGER NOT NULL,
                weekday INTEGER NOT NULL CHECK (weekday BETWEEN 1 AND 7),
                start_time TEXT NOT NULL,
                end_time TEXT NOT NULL,
                subject TEXT NOT NULL,
                teacher TEXT DEFAULT '',
                room TEXT DEFAULT '',
                notes TEXT DEFAULT '',
                FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS users (
                telegram_id INTEGER PRIMARY KEY,
                group_id INTEGER,
                FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE SET NULL
            );
            CREATE INDEX IF NOT EXISTS idx_lessons_group_day ON lessons(group_id, weekday, start_time);
            """)


def _execute(conn, sql: str, params=()):
    if _is_postgres():
        sql = sql.replace("?", "%s")
    return conn.execute(sql, params)


def list_groups():
    with connection() as conn:
        rows = _execute(conn, "SELECT id, name FROM groups ORDER BY name").fetchall()
        return [dict(r) for r in rows]


def create_group(name: str):
    name = name.strip()
    if not name:
        raise ValueError("Название группы не может быть пустым")
    with connection() as conn:
        if _is_postgres():
            cur = _execute(conn, "INSERT INTO groups(name) VALUES (?) RETURNING id", (name,))
            return cur.fetchone()["id"]
        cur = _execute(conn, "INSERT INTO groups(name) VALUES (?)", (name,))
        return cur.lastrowid


def delete_group(group_id: int):
    with connection() as conn:
        _execute(conn, "DELETE FROM groups WHERE id = ?", (group_id,))


def get_lessons(group_id: int, weekday: Optional[int] = None):
    with connection() as conn:
        base = """
            SELECT id, group_id, weekday, start_time, end_time,
                   subject, teacher, room, notes
            FROM lessons
            WHERE group_id = ?
        """
        if weekday is None:
            rows = _execute(conn, base + " ORDER BY weekday, start_time, id", (group_id,)).fetchall()
        else:
            rows = _execute(conn, base + " AND weekday = ? ORDER BY start_time, id", (group_id, weekday)).fetchall()
        return [dict(r) for r in rows]


def create_lesson(group_id, weekday, start_time, end_time, subject,
                  teacher="", room="", notes=""):
    with connection() as conn:
        sql = """
            INSERT INTO lessons
            (group_id, weekday, start_time, end_time, subject, teacher, room, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """
        if _is_postgres():
            sql += " RETURNING id"
            return _execute(conn, sql, (group_id, weekday, start_time, end_time, subject, teacher, room, notes)).fetchone()["id"]
        cur = _execute(conn, sql, (group_id, weekday, start_time, end_time, subject, teacher, room, notes))
        return cur.lastrowid


def update_lesson(lesson_id, weekday, start_time, end_time, subject,
                  teacher="", room="", notes=""):
    with connection() as conn:
        _execute(conn, """
            UPDATE lessons
            SET weekday=?, start_time=?, end_time=?, subject=?,
                teacher=?, room=?, notes=?
            WHERE id=?
        """, (weekday, start_time, end_time, subject, teacher, room, notes, lesson_id))


def delete_lesson(lesson_id):
    with connection() as conn:
        _execute(conn, "DELETE FROM lessons WHERE id = ?", (lesson_id,))


def set_user_group(telegram_id: int, group_id: int):
    with connection() as conn:
        _execute(conn, """
            INSERT INTO users(telegram_id, group_id)
            VALUES (?, ?)
            ON CONFLICT(telegram_id)
            DO UPDATE SET group_id=excluded.group_id
        """, (telegram_id, group_id))


def get_user_group(telegram_id: int):
    with connection() as conn:
        row = _execute(conn, "SELECT group_id FROM users WHERE telegram_id=?", (telegram_id,)).fetchone()
        return row["group_id"] if row else None


def get_group(group_id: int):
    with connection() as conn:
        row = _execute(conn, "SELECT id, name FROM groups WHERE id=?", (group_id,)).fetchone()
        return dict(row) if row else None
